graph TD;
    A[Start: Select Timeframe] --> B[Retrieve all Users' Availability];
    B --> C[Retrieve all Shifts within Timeframe];
    C --> D{For each Shift: Retrieve corresponding Staff_Required};
    D --> E[For each Shift_Type in Staff_Required];
    E --> X[Match Users Availability with Shift_Type];
    X --> F{Are there sufficient Users available?};
    F -->|If sufficient Users available| H[Create Staffing records];
    H --> J{Next Shift};
    F --> Y[Match Users flexible availability with Shift_Type];
    Y --> G{Are there sufficient Users available?};
    G -->|If sufficient Users available| H;
    G -->|If not sufficient Users| I[Create Open Staffing records];
    I --> J;
    J --> K{Are there more Shifts?};
    K -->|Yes| D;
    K -->|No| L{For each Day in Timeframe};
    L --> M[Select 2 Users as Backups];
    M --> N[Create Backup records];
    N --> O[Next Day];
    O --> P{Are there more Days?};
    P -->|Yes| L;
    P -->|No| Q[End];