flowchart TD
  A[Start] -->|1. Start de vrijgaveprocedure| B(Druk op de vrijgave knop)
  B -->|2. Selecteer de medewerker| C(Medewerker selecteren)
  C -->|3. Selecteer de periode| D(Periode selecteren)
  D -->|4. Bevestig de vrijgave| E[Vrijgave bevestigen]
  E -->|5 Vrijgave succesvol| F[Vrijgave succesvol]
  F -->|6. Eindig de procedure| G[Einde]